function Hd = Lp_filter(Fs,Fpass,Fstop)
%LP_FILTER 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 23.2 and DSP System Toolbox 23.2.
% Generated on: 23-Dec-2023 15:24:55

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
% Fs = 50000000000;  % Sampling Frequency

% Fpass = 100000000;       % Passband Frequency
% Fstop = 200000000;      % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
flag  = 'scale';         % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fpass Fstop]/(Fs/2), [1 0], [Dstop Dpass]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dfilt.dffir(b);

% [EOF]
